### ISSUE TITLE
Custom loading image not working

### ISSUE THREAD

**Issue by Cervator** [Terasology/PolyWorld#8]
At least it doesn't for me, anyway - tried to cleanup thoroughly just in case! But I still get the following logged:

```
00:06:05.907 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: engine:0.54.1-SNAPSHOT
00:06:05.908 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CommonWorld:0.1.3-SNAPSHOT
00:06:05.908 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Core:0.54.1-SNAPSHOT
00:06:05.908 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CoreSampleGameplay:0.54.1-SNAPSHOT
00:06:05.908 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: PolyWorld:0.6.1
00:06:12.730 [main] ERROR org.terasology.assets.AssetType - Failed to load asset 'engine:loadingBackground'
java.io.IOException: Invalid tile - must be square with power-of-two sides
	at org.terasology.world.block.tiles.TileFormat.load(TileFormat.java:51) ~[classes/:na]
	at org.terasology.world.block.tiles.TileFormat.load(TileFormat.java:38) ~[classes/:na]
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.AssetType.lambda$reload$1(AssetType.java:325) [gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.AssetType$$Lambda$46/1783083399.run(Unknown Source) ~[na:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_45]
	at org.terasology.assets.AssetType.reload(AssetType.java:323) [gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:352) [gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.AssetType.getAsset(AssetType.java:232) [gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:206) [gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.asset.Assets.get(Assets.java:75) [classes/:na]
	at org.terasology.world.block.tiles.WorldAtlasImpl.indexTile(WorldAtlasImpl.java:167) [classes/:na]
	at org.terasology.world.block.tiles.WorldAtlasImpl.<init>(WorldAtlasImpl.java:89) [classes/:na]
	at org.terasology.engine.modes.loadProcesses.RegisterBlocks.step(RegisterBlocks.java:55) [classes/:na]
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:243) [classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:430) [classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:358) [classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:145) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
00:06:13.287 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome OCEAN with short id 0.
```

It is actually kinda funny how the logging works out. `Failed to load asset 'engine:loadingBackground'` makes you think it is an engine issue, but that asset is overridden in PolyWorld. Wonder if there's a way we can catch overridden assets for better logging in this kind of case?

I finally get to add this to the lineup, woo! :-)

**Comment by msteiger** [comment]
Fixed by https://github.com/MovingBlocks/Terasology/pull/1867
